# -*- coding: utf-8 -*-
"""PruebasProyectoParques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qohLmexivUzt7FdoOAf7UTKil_CTVqRi
"""


contador_de_turnos = 0


#INICIO DEL JUEGO: Numero de jugadores
while True:
  try:
    jugadores1 = int(input("¿Cuántos jugadores habrán? (Seleccione de 2-4)"))
    if jugadores1 >= 2 and jugadores <= 4:
      break
    else:
      print("Debe seleccionar entre 2 y 4 jugadores")
  except ValueError:
    print("Debe ingresar un número")

fichas=4

#DADOS

print(carcel)
#MOVIMIENTOS
#movimientos = 0
#while True:
  #try:
    #if dado1=5 or dado2=5
      #movimientos = 1
      #break





#determina los colores de los jugadores


if jugadores1 == 3:

 del lista_de_judadores["jugadores"][3]

elif jugadores1 == 2: 

 del lista_de_judadores["jugadores"][2]
 
 del lista_de_judadores["jugadores"][3]


#turnos(funciona infinitamente pero funcionan  falta ver como hacer que solo se active cada cierto  tiempo 
# o despues de cierta accion si es haci se le puede quitar el while)




def turnos(lista_de_jugadores):

  global contador_de_turnos

  t = True
  while t:


   import random

    dado1 = random.randint(1,6) 
    dado2 = random.randint(1,6)
    print("Dado 1:", dado1)
    print("Dado 2:", dado2)

    if dado2 == dado1:
      print("puedes volver a tirar los dados")

    elif contador_de_turnos == 10:

      print("fin del juego")
      t = False

    else:

       primero = lista_de_jugadores.pop(0)   
       lista_de_jugadores.append(primero)     
        

    contador_de_turnos = contador_de_turnos + 1
   

    print (lista_de_jugadores) 


turnos(lista_de_jugadores)
