# -*- coding: utf-8 -*-
"""PruebasProyectoParques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qohLmexivUzt7FdoOAf7UTKil_CTVqRi
"""





#INICIO DEL JUEGO: Numero de jugadores
while True:
  try:
    jugadores = int(input("¿Cuántos jugadores habrán? (Seleccione de 2-4)"))
    if jugadores >= 2 and jugadores <= 4:
      break
    else:
      print("Debe seleccionar entre 2 y 4 jugadores")
  except ValueError:
    print("Debe ingresar un número")

fichas=4

#DADOS
import random
dado1 = random.randint(1,6)
dado2 = random.randint(1,6)
print("Dado 1:", dado1)
print("Dado 2:", dado2)

for i in range(jugadores):
  carcel=[1,2,3,4]

print(carcel)
#MOVIMIENTOS
#movimientos = 0
#while True:
  #try:
    #if dado1=5 or dado2=5
      #movimientos = 1
      #break


if dado2 == dado1:
  



#determina los colores de los jugadores


lista_de_judadores = [rojo,azul,amarillo,verde]

if jugadores == 3:

 lista_de_judadores.remove(verde)

elif jugadores == 2: 

 lista_de_judadores.remove(amarillo) 


#turnos(funciona infinitamente pero funcionan  falta ver como hacer que solo se active cada cierto  tiempo 
# o despues de cierta accion si es haci se le puede quitar el while)


#def turnos(lista_de_judadores)

 # while len(lista_de_judadores) > 1:

  #3 primero = lista_de_judadores.pop(0)   
  # lista_de_judadores.append(primero)     
   # print(lista_de_judadores)     
    
 # print(lista_de_judadores)

#turnos(lista_de_judadores)