# -*- coding: utf-8 -*-
"""PruebasProyectoParques.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qohLmexivUzt7FdoOAf7UTKil_CTVqRi
"""

#INICIO DEL JUEGO: Numero de jugadores
while True:
  try:
    jugadores = int(input("¿Cuántos jugadores habrán? (Seleccione de 2-4)"))
    if jugadores >= 2 and jugadores <= 4:
      break
    else:
      print("Debe seleccionar entre 2 y 4 jugadores")
  except ValueError:
    print("Debe ingresar un número")

fichas=4

#DADOS
import random
dado1 = random.randint(1,6)
dado2 = random.randint(1,6)
print("Dado 1:", dado1)
print("Dado 2:", dado2)

for i in range(jugadores):
  carcel=[1,2,3,4]

print(carcel)
#MOVIMIENTOS
#movimientos = 0
#while True:
  #try:
    #if dado1=5 or dado2=5
      #movimientos = 1
      #break